services:
  - type: web
    name: vs-sistema
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_APP_ID
        value: plataforma-ad
