import { Database, Pencil, PlusCircle, Search, Trash2 } from 'lucide-react';
import { baseLabels, initialBaseState } from '../../data/initialStates';
import Button from '../ui/Button';
import Field from '../ui/Field';

const tabs = Object.keys(baseLabels);

export default function BaseTables({ data, activeTab, setActiveTab, formData, setFormData, editId, setEditId, searchTerm, setSearchTerm, onSave, onDelete, onEdit }) {
  const records = data[activeTab] || [];
  const filtered = records.filter(item => item.nome?.toLowerCase().includes(searchTerm.toLowerCase()));
  return <div className="space-y-8"><div className="bg-white p-6 rounded-3xl border border-stone-200 shadow-sm flex flex-wrap gap-2">{tabs.map(tab => <button key={tab} onClick={() => { setActiveTab(tab); setEditId(null); setFormData(initialBaseState); setSearchTerm(''); }} className={`px-4 py-2.5 rounded-xl font-black text-[10px] uppercase transition-all ${activeTab === tab ? 'bg-amber-700 text-white shadow-md' : 'bg-[#faf8f5] text-stone-500 hover:bg-stone-100 border border-stone-200'}`}>{baseLabels[tab]}</button>)}</div><div className="grid grid-cols-1 lg:grid-cols-12 gap-8"><div className="lg:col-span-5"><div className="p-8 rounded-[32px] border shadow-sm sticky top-24 bg-white border-stone-200"><h3 className="text-xl font-black flex items-center gap-2 text-stone-800 mb-6">{editId ? <Pencil/> : <PlusCircle/>}{editId ? 'Editando' : 'Novo'} Registro</h3><form onSubmit={onSave} className="space-y-4"><Field label={`Nome - ${baseLabels[activeTab]}`} value={formData.nome} onChange={e => setFormData({...formData, nome: e.target.value})} required/><Button type="submit" variant={editId ? 'success' : 'primary'} className="w-full py-4 text-xs uppercase tracking-widest">{editId ? 'Salvar Alterações' : 'Gravar Registro'}</Button></form></div></div><div className="lg:col-span-7 space-y-4"><div className="flex items-center gap-4 bg-white p-5 rounded-3xl border border-stone-200 shadow-sm"><Search className="text-stone-300" size={20}/><input type="text" placeholder="Pesquisar registros..." className="flex-1 outline-none text-sm font-bold text-stone-600 placeholder:text-stone-300" value={searchTerm} onChange={e => setSearchTerm(e.target.value)} /></div><div className="space-y-3">{filtered.map(item => <div key={item.id} className="p-6 rounded-[28px] border border-stone-200 bg-white shadow-sm flex justify-between items-center"><div><h4 className="font-black text-stone-800 text-lg">{item.nome}</h4><p className="text-[10px] text-stone-500 font-bold uppercase tracking-wider mt-1">Registro base do sistema</p></div><div className="flex gap-2"><button onClick={() => onEdit(item)} className="p-3 text-stone-400 bg-[#faf8f5] rounded-xl hover:bg-amber-600 hover:text-white"><Pencil size={18}/></button><button onClick={() => onDelete(activeTab, item.id)} className="p-3 text-stone-400 bg-[#faf8f5] rounded-xl hover:bg-red-500 hover:text-white"><Trash2 size={18}/></button></div></div>)}{filtered.length === 0 && <div className="p-8 text-center border-2 border-dashed border-stone-200 rounded-3xl bg-[#faf8f5]"><Database className="mx-auto text-stone-300 mb-2" size={32}/><p className="text-stone-500 font-medium text-sm">Ainda não há registros nesta categoria.</p></div>}</div></div></div></div>;
}
